before:
  hooks:
    - go mod tidy -compat=1.17

builds:
- goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  ignore:
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64
    - goos: darwin
      goarch: arm
    - goos: darwin
      goarch: arm
    - goos: linux
      goarch: arm
      goarm: 7


dockers:
  - image_templates:
    - "ghcr.io/suprememoocow/prom2mqtt:latest-amd64"
    - "ghcr.io/suprememoocow/prom2mqtt:{{ .Tag }}-amd64"
    goos: linux
    goarch: amd64
  - image_templates:
    - "ghcr.io/suprememoocow/prom2mqtt:latest-arm64"
    - "ghcr.io/suprememoocow/prom2mqtt:{{ .Tag }}-arm64"
    goos: linux
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/suprememoocow/prom2mqtt:latest"
    image_templates:
    - "ghcr.io/suprememoocow/prom2mqtt:latest-amd64"
    - "ghcr.io/suprememoocow/prom2mqtt:latest-arm64"

  - name_template: "ghcr.io/suprememoocow/prom2mqtt:{{ .Tag }}"
    image_templates:
    - "ghcr.io/suprememoocow/prom2mqtt:{{ .Tag }}-amd64"
    - "ghcr.io/suprememoocow/prom2mqtt:{{ .Tag }}-arm64"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
