groups:
  - name: weather_station
    interval: 1m
    queries:
      - topic: 'avitrack/rain_1h'
        expr: round(sum(increase(avitrack_rain_mm[1h])))
        decimal_places: 1

      - topic: 'avitrack/rained_last_30m'
        expr: sum(increase(avitrack_rain_mm[30m])) > bool 0
        decimal_places: 0

      - topic: 'avitrack/rain_24h'
        expr: round(sum(increase(avitrack_rain_mm[24h])))
        decimal_places: 1

      # Air Pressure must be in the range 700 to 1100 hPa.
      - topic: 'avitrack/air_pressure_mbar'
        expr: clamp_max(clamp_min(avg(avitrack_atmospheric_pressure_mbar), 700), 1100)
        decimal_places: 0

      - topic: 'avitrack/wind_direction_deg'
        expr: avitrack_wind_direction_deg
        decimal_places: 1

      - topic: 'avitrack/avg_wind_speed_kmh'
        expr: avg(avitrack_avg_wind_speed_kmh)
        decimal_places: 1

      # Current temperature must be in the range 0 to 100 degrees Celsius to a maximum of 1dp.
      - topic: 'avitrack/temperature_celsius'
        expr: |
          clamp_max(clamp_min(
            avg(avitrack_temperature_celsius),
          -50), 100)
        decimal_places: 1

      # Current relative humidity must be in the range 0 to 100 percent with no decimal places.
      - topic: 'avitrack/relative_humidity'
        expr: |
          clamp_max(clamp_min(
            avg(avitrack_relative_humidity * 100),
          0), 100)
        decimal_places: 0
